name=ST7735_Simple_Menu
version=0.1.0
author=Sadman Tariq <sadmantariq@gmail.com>
maintainer=Sadman Tariq <sadmantariq@gmail.com>
sentence=A simple menu library for the ST7735 TFT module.
category=Display
url=https://github.com/SadmanTariq/ST7735_Simple_Menu
depends=Adafruit ST7735 and ST7789 Library
